var products = [
  {
    p_id: 101,
    p_name: "Analogue Watch (Women)",
    p_price: 1999,
    p_image: "C:/xampp/htdocs/ecomweb/images/c_accessory_1.jpg",
    p_quantity: 0,
  },
  {
    p_id: 102,
    p_name: "Sunglasses",
    p_price: 150,
    p_image: "C:/xampp/htdocs/ecomweb/images/c_accessory_2.jpg",
    p_quantity: 0,
  },
  {
    p_id: 103,
    p_name: "Men Suit",
    p_price: 6240,
    p_image: "C:/xampp/htdocs/ecomweb/images/c_best_selling_1.jpg",
    p_quantity: 0,
  },
  {
    p_id: 104,
    p_name: "Black Jacket",
    p_price: 2500,
    p_image: "C:/xampp/htdocs/ecomweb/images/c_best_selling_2.jpg",
    p_quantity: 0,
  },
  {
    p_id: 105,
    p_name: "Gray Shirt",
    p_price: 500,
    p_image: "C:/xampp/htdocs/ecomweb/images/c_best_selling_3.jpg",
    p_quantity: 0,
  },
  {
    p_id: 106,
    p_name: "Tote Bag",
    p_price: 2500,
    p_image: "C:/xampp/htdocs/ecomweb/images/c_on_sale_1.jpg",
    p_quantity: 0,
  },
  {
    p_id: 107,
    p_name: "Black Hoodie",
    p_price: 3199,
    p_image: "C:/xampp/htdocs/ecomweb/images/c_on_sale_2.jpg",
    p_quantity: 0,
  },
  {
    p_id: 108,
    p_name: "Sport Shoes",
    p_price: 2999,
    p_image: "C:/xampp/htdocs/ecomweb/images/c_on_sale_3.jpg",
    p_quantity: 0,
  },
  {
    p_id: 109,
    p_name: "Denim Jeans",
    p_price: 3450,
    p_image: "images/c_pant_girl.png",
    p_quantity: 0,
  },
  {
    p_id: 110,
    p_name: "Halter Neck Vest",
    p_price: 2499,
    p_image: "C:/xampp/htdocs/ecomweb/images/c_polo-shirt.png",
    p_quantity: 0,
  },
  {
    p_id: 111,
    p_name: "Ruched Detail Top",
    p_price: 1499,
    p_image: "C:/xampp/htdocs/ecomweb/images/c_shirt-girl.png",
    p_quantity: 0,
  },
  {
    p_id: 112,
    p_name: "Set of Hoodies",
    p_price: 6999,
    p_image: "C:/xampp/htdocs/ecomweb/images/c_sweats.jpg",
    p_quantity: 0,
  },
  {
    p_id: 201,
    p_name: "Black Shacket",
    p_price: 1900,
    p_image: "images/c_t-shirt_men.png",
    p_quantity: 0,
  },
  {
    p_id: 202,
    p_name: "Blue Shirt",
    p_price: 2995,
    p_image: "images/c_top_rated_1.jpg",
    p_quantity: 0,
  },
  {
    p_id: 203,
    p_name: "Casio Smart Outdoor Smartwatch",
    p_price: 2499,
    p_image: "images/c_top_rated_2.jpg",
    p_quantity: 0,
  },
  {
    p_id: 204,
    p_name: "Red Hoodie",
    p_price: 1995,
    p_image: "images/c_top_rated_3.jpg",
    p_quantity: 0,
  },
  {
    p_id: 205,
    p_name: "Black Shirt",
    p_price: 1799,
    p_image: "images/c_tunic-shirt_girl.png",
    p_quantity: 0,
  },
  {
    p_id: 206,
    p_name: "Blue Polka Dot Blouse",
    p_price: 2595,
    p_image: "images/c_undershirt.png",
    p_quantity: 0,
  },
  {
    p_id: 210,
    p_name: "Black Sheer Top ",
    p_price: 2599,
    p_image: "images/c_western-shirt.png",
    p_quantity: 0,
  },
];
